In [40]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from ipywidgets import interact
import ipywidgets as widgets
from ipywidgets import interact, FloatSlider
from IPython.display import display, clear_output

# Load the data
file_path = 'data/Hurricane_Irene_Hudson_River.xlsx'
do_data = pd.read_excel('data/Hurricane_Irene_Hudson_River.xlsx', sheet_name = 5).drop(['Piermont D.O. (ppm)'], axis = 1)
rainfall_data = pd.read_excel(file_path, sheet_name='Rainfall').drop(['Piermont  Rainfall Daily Accumulation (Inches)'], axis = 1)
turbidity_data = pd.read_excel(file_path, sheet_name='Turbidity').drop(['Piermont Turbidity in NTU'], axis = 1)


# Merge the two datasets
data = rainfall_data.merge(turbidity_data, on = 'Date Time (ET)')
data = data.merge(do_data, on = 'Date Time (ET)')
data.head()

# Update the column names 
data.columns = ['date', 'albany_rainfall', 'norrie_rainfall', 'albany_turbidity', 'norrie_turbidity','albany_do', 'norrie_do']

# Convert data to datetime format and set it as index
data['date'] = pd.to_datetime(data['date'])

data.set_index('date', inplace=True)

,albany_rainfall,norrie_rainfall,albany_turbidity,norrie_turbidity,albany_do,norrie_do
date,,,,,,
2011-08-25 00:00:00,0.000000,0.000000,4.0,9.3,7.68,7.81
2011-08-25 00:15:00,0.000000,0.000000,3.9,8.4,7.60,7.73
2011-08-25 00:30:00,0.000000,0.000000,4.3,7.9,7.57,7.63
2011-08-25 00:45:00,0.000000,0.000000,4.7,8.1,7.72,7.67
2011-08-25 01:00:00,0.000000,0.000000,4.4,8.4,7.74,7.63
...,...,...,...,...,...,...
2011-09-05 22:45:00,0.629999,1.219998,47.2,144.1,8.73,6.84
2011-09-05 23:00:00,0.639999,1.239998,56.7,139.7,8.76,6.78
2011-09-05 23:15:00,0.649999,1.259997,47.0,141.2,8.66,6.83
2011-09-05 23:30:00,0.679999,1.269997,48.7,127.9,8.75,6.79
2011-09-05 23:45:00,0.719999,1.289997,49.5,149.0,8.68,6.78

In [33]:
# Define predictors and the target variable
X = data[['albany_rainfall', 'norrie_rainfall', 'albany_do', 'norrie_do']]  # Adjust as needed
y = data['albany_turbidity']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and fit the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"R-squared: {r2_score(y_test, y_pred)}")

RMSE: 180.9663057607227
R-squared: 0.632779560169372

In [56]:
# Create a widget for selecting predictors
predictor_selector = widgets.SelectMultiple(
    options=data.columns,
    value=[data.columns[0]],  
    description='Predictors'
)

# Create a dropdown for selecting the target variable
target_selector = widgets.Dropdown(
    options=data.columns,
    value=data.columns[1],  
    description='Target',
)

# Button to evaluate the model
evaluate_button = widgets.Button(description="Evaluate Model")

# Output widget to display results
output = widgets.Output()

# Define the function to handle button clicks
def evaluate_model(b):
    with output:
        clear_output(wait=True)
        
        # Make sure the target is not in the predictors
        selected_predictors = [item for item in predictor_selector.value]
        if target_selector.value in selected_predictors:
            print("Target variable must not be in the predictors.")
            return
        
        # Prepare the data
        X = data[selected_predictors]
        y = data[target_selector.value]
        
        # Split data into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        # Create and fit the model
        model = LinearRegression()
        model.fit(X_train, y_train)
        
        # Predict and calculate R^2 and MSE
        y_pred = model.predict(X_test)
        r2 = r2_score(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        
        # Display the R^2 score and MSE
        print(f"R^2: {r2:.4f}")
        print(f"MSE: {mse:.4f}")


        plt.scatter(y_test, y_pred) # SOLUTION NO PROMPT
        plt.xlabel('Actual') # SOLUTION NO PROMPT
        plt.ylabel('Predicted') # SOLUTION NO PROMPT
        plt.title('Actual vs Predicted') # SOLUTION NO PROMPT
        plt.show() # SOLUTION NO PROMPT


# Display the widgets and connect the button to the function
display(predictor_selector, target_selector, evaluate_button, output)
evaluate_button.on_click(evaluate_model)

SelectMultiple(description='Predictors', index=(0,), options=('albany_rainfall', 'norrie_rainfall', 'albany_tu…

Dropdown(description='Target', index=1, options=('albany_rainfall', 'norrie_rainfall', 'albany_turbidity', 'no…

Button(description='Evaluate Model', style=ButtonStyle())

Output()